version: '3.3'
services:
    blueocean:
        container_name: MyJenkins2
        ports:
            - '8080:8080'
        user: root
        volumes:
            - '/Users/rajee/Desktop/ocean_data:/var/jenkins_home'
            - '/var/run/docker.sock:/var/run/docker.sock'
            - '$HOME:/home'
        image: jenkinsci/blueocean
        depends_on:
            - elasticsearch

    elasticsearch:
        container_name: ElasticSearch1
        ports:
            - '9200:9200'
            - '9300:9300'
        volumes:
            - elasticsearch:/usr/share/elasticsearch/data
        environment:
            - cluster.routing.allocation.disk.watermark.low=500mb
            - cluster.routing.allocation.disk.watermark.high=300mb
            - cluster.routing.allocation.disk.watermark.flood_stage=200mb
        image: elasticsearch:6.8.8

    kibana:
        container_name: Kibana1
        ports:
            - '5601:5601'
        image: kibana:6.8.8
        depends_on:
            - blueocean
            - elasticsearch


    helloworld:
        build: ./helloworld_project
        container_name: HelloWorldApp
        ports:
            - '8000:8000'
        volumes:
            - './helloworld_project/:/helloworld_project/'
        command: python manage.py runserver 0.0.0.0:8000
        depends_on:
            - elasticsearch

volumes:
    elasticsearch:
